project_id = "vtumlsosuhfsxkrhnibw"

[functions.setup-demo-accounts]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = true

[functions.send-candidate-email]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.parse-job-description]
verify_jwt = true

[functions.generate-job-description]
verify_jwt = true

[functions.parse-resume]
verify_jwt = true

[functions.match-candidates]
verify_jwt = true
